spring.application.name=campaignpro-backend

server.port=${PORT:8080}

spring.mongodb.uri=mongodb://localhost:27017/campaignpro

spring.data.mongodb.auto-index-creation=true

jwt.secret=${JWT_SECRET:mysupersecretkeymysupersecretkey12345}
jwt.expiration=${JWT_EXPIRATION:3600000}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs